name: Release and Publish

on:
  push:
    branches:
      - main      # Stable releases
      - develop   # Pre-releases
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease
      prerelease_tag:
        description: 'Pre-release tag (alpha, beta, rc)'
        required: false
        default: 'beta'
        type: string
      dry_run:
        description: 'Dry run (build only, do not publish)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  # Check if PR author is a maintainer
  check-permissions:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    outputs:
      is-maintainer: ${{ steps.check.outputs.is-maintainer }}
    steps:
      - name: Check if PR author is maintainer
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Check if the PR author has write access to the repository
              const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: context.payload.pull_request.user.login
              });
            
              console.log(`User: ${context.payload.pull_request.user.login}`);
              console.log(`Permission level: ${permission.permission}`);
            
              // Allow admin, maintain, and write permissions
              const isMaintainer = ['admin', 'maintain', 'write'].includes(permission.permission);
            
              core.setOutput('is-maintainer', isMaintainer);
            
              if (!isMaintainer) {
                console.log('❌ User does not have maintainer permissions');
              } else {
                console.log('✅ User has maintainer permissions');
              }
            
              return isMaintainer;
            } catch (error) {
              console.error('Error checking permissions:', error);
              core.setOutput('is-maintainer', false);
              return false;
            }

  release:
    runs-on: ubuntu-latest
    needs: [ check-permissions ]
    if: |
      always() && (
        github.event_name == 'workflow_dispatch' || 
        github.ref == 'refs/heads/main' || 
        github.ref == 'refs/heads/develop' || 
        (github.event_name == 'pull_request' && needs.check-permissions.outputs.is-maintainer == 'true')
      )

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build all packages
        run: |
          echo "🔨 Building ng-openapi..."
          npx nx run ng-openapi:build
          
          echo "🔨 Building http-resource plugin..."
          npx nx run http-resource:build

      - name: Verify build outputs
        run: |
          echo "📦 ng-openapi build output:"
          ls -la dist/packages/ng-openapi/
          cat dist/packages/ng-openapi/package.json
          
          echo "📦 http-resource build output:"
          ls -la dist/packages/plugins/http-resource/
          cat dist/packages/plugins/http-resource/package.json

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine release parameters
        id: release-params
        run: |
          # Determine release parameters based on trigger
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            RELEASE_TYPE="${{ github.event.inputs.release_type }}"
            PRERELEASE_TAG="${{ github.event.inputs.prerelease_tag }}"
            IS_PRERELEASE="${{ github.event.inputs.release_type == 'prerelease' }}"
          
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # PR prerelease with branch name, PR number, and commit SHA for uniqueness
            BRANCH_NAME="${{ github.head_ref }}"
            PR_NUMBER="${{ github.event.number }}"
            SHORT_SHA="${{ github.event.pull_request.head.sha }}"
            SHORT_SHA=${SHORT_SHA:0:7}  # Use first 7 chars of SHA
          
            # Sanitize branch name for npm tag (replace special chars with dashes)
            SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
          
            RELEASE_TYPE="prerelease"
            PRERELEASE_TAG="pr-${PR_NUMBER}-${SANITIZED_BRANCH}-${SHORT_SHA}"
            IS_PRERELEASE="true"
          
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            RELEASE_TYPE="prerelease"
            PRERELEASE_TAG="beta"
            IS_PRERELEASE="true"
          
          else
            # main branch - stable release
            RELEASE_TYPE="patch"
            PRERELEASE_TAG=""
            IS_PRERELEASE="false"
          fi
          
          echo "Release type: $RELEASE_TYPE"
          echo "Prerelease tag: $PRERELEASE_TAG"
          echo "Is prerelease: $IS_PRERELEASE"
          
          # Set outputs
          {
            echo "release_type=$RELEASE_TYPE"
            echo "prerelease_tag=$PRERELEASE_TAG"
            echo "is_prerelease=$IS_PRERELEASE"
          } >> $GITHUB_OUTPUT

      - name: Update ng-openapi version
        id: version-ng-openapi
        working-directory: packages/ng-openapi
        run: |
          # Update version based on release type
          if [[ "${{ steps.release-params.outputs.is_prerelease }}" == "true" ]]; then
            npm version prerelease --preid="${{ steps.release-params.outputs.prerelease_tag }}" --no-git-tag-version
            NPM_TAG="${{ steps.release-params.outputs.prerelease_tag }}"
          else
            npm version "${{ steps.release-params.outputs.release_type }}" --no-git-tag-version
            NPM_TAG="latest"
          fi
          
          # Get the new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "ng-openapi new version: $NEW_VERSION"
          
          # Set outputs
          {
            echo "version=$NEW_VERSION"
            echo "npm_tag=$NPM_TAG"
          } >> $GITHUB_OUTPUT

      - name: Update http-resource version
        id: version-http-resource
        working-directory: packages/plugins/http-resource
        run: |
          # Update version based on release type
          if [[ "${{ steps.release-params.outputs.is_prerelease }}" == "true" ]]; then
            npm version prerelease --preid="${{ steps.release-params.outputs.prerelease_tag }}" --no-git-tag-version
            NPM_TAG="${{ steps.release-params.outputs.prerelease_tag }}"
          else
            npm version "${{ steps.release-params.outputs.release_type }}" --no-git-tag-version
            NPM_TAG="latest"
          fi
          
          # Get the new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "http-resource new version: $NEW_VERSION"
          
          # Set outputs
          {
            echo "version=$NEW_VERSION"
            echo "npm_tag=$NPM_TAG"
          } >> $GITHUB_OUTPUT

      - name: Copy updated package.json files to dist
        run: |
          echo "📋 Copying updated package.json files..."
          cp packages/ng-openapi/package.json dist/packages/ng-openapi/package.json
          cp packages/plugins/http-resource/package.json dist/packages/plugins/http-resource/package.json
          
          echo "✅ Updated ng-openapi version: $(cat dist/packages/ng-openapi/package.json | jq -r '.version')"
          echo "✅ Updated http-resource version: $(cat dist/packages/plugins/http-resource/package.json | jq -r '.version')"

      - name: Publish ng-openapi to NPM
        if: github.event.inputs.dry_run != 'true'
        working-directory: dist/packages/ng-openapi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "📦 Publishing ng-openapi version ${{ steps.version-ng-openapi.outputs.version }} with tag ${{ steps.version-ng-openapi.outputs.npm_tag }}"
          npm publish --tag ${{ steps.version-ng-openapi.outputs.npm_tag }} --access public
          echo "✅ ng-openapi published successfully!"

      - name: Publish http-resource to NPM
        if: github.event.inputs.dry_run != 'true'
        working-directory: dist/packages/plugins/http-resource
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "📦 Publishing @ng-openapi/http-resource version ${{ steps.version-http-resource.outputs.version }} with tag ${{ steps.version-http-resource.outputs.npm_tag }}"
          npm publish --tag ${{ steps.version-http-resource.outputs.npm_tag }} --access public
          echo "✅ @ng-openapi/http-resource published successfully!"

      - name: Create Git tags and push
        if: github.event.inputs.dry_run != 'true' && github.event_name != 'pull_request'
        run: |
          echo "🏷️ Creating Git tags and committing changes..."
          git add packages/ng-openapi/package.json packages/plugins/http-resource/package.json
          git commit -m "chore: release ng-openapi@${{ steps.version-ng-openapi.outputs.version }} and @ng-openapi/http-resource@${{ steps.version-http-resource.outputs.version }}"
          
          # Create tags for both packages
          git tag "ng-openapi@${{ steps.version-ng-openapi.outputs.version }}"
          git tag "@ng-openapi/http-resource@${{ steps.version-http-resource.outputs.version }}"
          
          git push origin HEAD --tags
          echo "✅ Git tags created and pushed"

      - name: Create GitHub Release for ng-openapi
        if: github.event.inputs.dry_run != 'true' && github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ng-openapi@${{ steps.version-ng-openapi.outputs.version }}
          name: ng-openapi v${{ steps.version-ng-openapi.outputs.version }}
          body: |
            ## 🚀 ng-openapi v${{ steps.version-ng-openapi.outputs.version }}
            
            ### 📦 Installation
            ```bash
            # Install this version
            npm install ng-openapi@${{ steps.version-ng-openapi.outputs.version }} --save-dev
            
            # Install latest stable
            npm install ng-openapi --save-dev
            ```
            
            ### 🛠️ Usage
            ```bash
            ng-openapi --help
            ng-openapi -i swagger.json -o ./src/api
            ng-openapi -c openapi.config.ts
            ```
            
            ### 🔗 Links
            - 📚 [NPM Package](https://www.npmjs.com/package/ng-openapi)
            - 📖 [Documentation](https://ng-openapi.dev/)
            - 🐛 [Report Issues](https://github.com/${{ github.repository }}/issues)
            
            ### 📋 Other Packages Released
            - **@ng-openapi/http-resource**: v${{ steps.version-http-resource.outputs.version }}
          prerelease: ${{ steps.release-params.outputs.is_prerelease == 'true' }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release for http-resource
        if: github.event.inputs.dry_run != 'true' && github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "@ng-openapi/http-resource@${{ steps.version-http-resource.outputs.version }}"
          name: "@ng-openapi/http-resource v${{ steps.version-http-resource.outputs.version }}"
          body: |
            ## 🚀 @ng-openapi/http-resource v${{ steps.version-http-resource.outputs.version }}
            
            HTTP Resource plugin for ng-openapi - Angular HTTP utilities with caching and state management.
            
            ### 📦 Installation
            ```bash
            # Install this version
            npm install @ng-openapi/http-resource@${{ steps.version-http-resource.outputs.version }}
            
            # Install latest stable
            npm install @ng-openapi/http-resource
            ```
            
            ### 🛠️ Usage
            ```typescript
            import { HttpResourceGenerator } from '@ng-openapi/http-resource';
            
            const config: GeneratorConfig = {
              input: './swagger.json',
              output: './src/api',
              plugins: [HttpResourceGenerator],
              options: { /* ... */ }
            };
            ```
            
            ### 🔗 Links
            - 📚 [NPM Package](https://www.npmjs.com/package/@ng-openapi/http-resource)
            - 📖 [Documentation](https://ng-openapi.dev/plugins/http-resource)
            - 🐛 [Report Issues](https://github.com/${{ github.repository }}/issues)
            
            ### 📋 Other Packages Released
            - **ng-openapi**: v${{ steps.version-ng-openapi.outputs.version }}
          prerelease: ${{ steps.release-params.outputs.is_prerelease == 'true' }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR with release info
        if: github.event_name == 'pull_request' && github.event.inputs.dry_run != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## 🚀 PR Prerelease Published
            
            Multiple packages have been published for this PR:
            
            ### 📦 ng-openapi
            **Version**: \`v${{ steps.version-ng-openapi.outputs.version }}\`
            **NPM Tag**: \`${{ steps.version-ng-openapi.outputs.npm_tag }}\`
            
            \`\`\`bash
            npm install ng-openapi@${{ steps.version-ng-openapi.outputs.version }} --save-dev
            \`\`\`
            
            ### 📦 @ng-openapi/http-resource
            **Version**: \`v${{ steps.version-http-resource.outputs.version }}\`
            **NPM Tag**: \`${{ steps.version-http-resource.outputs.npm_tag }}\`
            
            \`\`\`bash
            npm install @ng-openapi/http-resource@${{ steps.version-http-resource.outputs.version }}
            \`\`\`
            
            **Commit**: \`${{ github.event.pull_request.head.sha }}\`
            
            ### 🔗 Links
            - [ng-openapi NPM](https://www.npmjs.com/package/ng-openapi/v/${{ steps.version-ng-openapi.outputs.version }})
            - [@ng-openapi/http-resource NPM](https://www.npmjs.com/package/@ng-openapi/http-resource/v/${{ steps.version-http-resource.outputs.version }})
            - [All ng-openapi versions](https://www.npmjs.com/package/ng-openapi?activeTab=versions)
            - [All http-resource versions](https://www.npmjs.com/package/@ng-openapi/http-resource?activeTab=versions)
            
            > These versions are unique to commit \`${{ github.event.pull_request.head.sha }}\` and will not conflict with other releases.
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Comment on PR if not maintainer
        if: github.event_name == 'pull_request' && needs.check-permissions.outputs.is-maintainer != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## ⚠️ PR Prerelease Skipped
            
            This PR was not published to NPM because the author does not have maintainer permissions.
            
            **Note**: Only repository maintainers (with write, maintain, or admin access) can trigger automatic PR releases.
            
            **Packages that would have been published:**
            - ng-openapi
            - @ng-openapi/http-resource
            
            If you believe this is an error, please contact a maintainer.
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Summary
        run: |
          echo "## 🎉 Multi-Package Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 ng-openapi" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: v${{ steps.version-ng-openapi.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **NPM Tag**: ${{ steps.version-ng-openapi.outputs.npm_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **NPM Package**: https://www.npmjs.com/package/ng-openapi" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 @ng-openapi/http-resource" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: v${{ steps.version-http-resource.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **NPM Tag**: ${{ steps.version-http-resource.outputs.npm_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **NPM Package**: https://www.npmjs.com/package/@ng-openapi/http-resource" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🛠️ Release Configuration" >> $GITHUB_STEP_SUMMARY
          echo "- **Prerelease**: ${{ steps.release-params.outputs.is_prerelease }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Release Type**: ${{ steps.release-params.outputs.release_type }}" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ github.event.inputs.dry_run }}" == "true" ]]; then
            echo "- **Dry Run**: ✅ No actual publishing occurred" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Published**: ✅ All packages successfully published to NPM" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🔀 PR Release Details" >> $GITHUB_STEP_SUMMARY
            echo "- **PR Release**: ✅ These are PR prereleases" >> $GITHUB_STEP_SUMMARY
            echo "- **Commit SHA**: ${{ github.event.pull_request.head.sha }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Install Commands**:" >> $GITHUB_STEP_SUMMARY
            echo "  - \`npm install ng-openapi@${{ steps.version-ng-openapi.outputs.version }} --save-dev\`" >> $GITHUB_STEP_SUMMARY
            echo "  - \`npm install @ng-openapi/http-resource@${{ steps.version-http-resource.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          fi